import oppo9 from '../assets/oppo9.jpg';
import oppo12 from '../assets/oppo12.jpg';
import oppoReno from '../assets/oppoReno.jpg';
import oppo55 from '../assets/oppo55.jpg';
import note20 from '../assets/note20.jpg';
// import svg from '../assets/like.svg';

export const phones = [
  {
    name: 'Oppo A9',
    // like: svg,
    id: oppo9,
    manufacturer: 'Oppo',
    color: 'Синий',
    price: '3',
    amount: '5',
    button: 'Добавить в корзину',
  },
  {
    name: 'Oppo A12',
    // like: svg,
    id: oppo12,
    manufacturer: 'Oppo',
    color: 'Черный',
    price: '2',
    amount: '3',
    button: 'Добавить в корзину',
  },
  {
    name: 'Oppo Reno7',
    // like: svg,
    id: oppoReno,
    manufacturer: 'Oppo',
    color: 'Голубой',
    price: '3',
    amount: '7',
    button: 'Добавить в корзину',
  },
  {
    name: 'Oppo A55',
    // like: svg,
    id: oppo55,
    manufacturer: 'Oppo',
    color: 'Серый',
    price: '2',
    amount: '4',
    button: 'Добавить в корзину',
  },
  {
    name: 'Samsung Galaxy Note20',
    // like: svg,
    id: note20,
    manufacturer: 'Samsung',
    color: 'Серый',
    price: '4',
    amount: '8',
    button: 'Добавить в корзину',
  },
  {
    name: 'Samsung S22 ultra',
    // like: svg,
    id: note20,
    manufacturer: 'Samsung',
    color: 'Синий',
    price: '4',
    amount: '7',
    button: 'Добавить в корзину',
  },
  {
    name: 'Samsung S21',
    // like: svg,
    id: oppoReno,
    manufacturer: 'Samsung',
    color: 'Черный',
    price: '3',
    amount: '5',
    button: 'Добавить в корзину',
  },
  {
    name: 'iPhone 13',
    // like: svg,
    id: oppoReno,
    manufacturer: 'Apple',
    color: 'Серый',
    price: '3',
    amount: '2',
    button: 'Добавить в корзину',
  },
  {
    name: 'iPhone 12',
    // like: svg,
    id: oppoReno,
    manufacturer: 'Apple',
    color: 'Черный',
    price: '2',
    amount: '1',
    button: 'Добавить в корзину',
  },
  {
    name: 'iPhone 13 Pro Max',
    // like: svg,
    id: oppoReno,
    manufacturer: 'Apple',
    color: 'Голубой',
    price: '3',
    amount: '8',
    button: 'Добавить в корзину',
  },
  {
    name: 'iPhone 12 mini',
    // like: svg,
    id: oppoReno,
    manufacturer: 'Apple',
    color: 'Черный',
    price: '2',
    amount: '2',
    button: 'Добавить в корзину',
  },
  {
    name: 'Samsung A22',
    // like: svg,
    id: oppoReno,
    manufacturer: 'Samsung',
    color: 'Голубой',
    price: '3',
    amount: '2',
    button: 'Добавить в корзину',
  },
];
